name: vcpkg-setup
runs:
  using: 'composite'
  steps:
    - run: |
        cd $VCPKG_INSTALLATION_ROOT
        git fetch
        git reset --hard ${{ env.VCPKG_REVISION }}
        ./bootstrap-vcpkg.sh -disableMetrics
      shell: bash
