name: Build

on:
- push
- pull_request

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_REVISION: 6d332a018c433fad20822ff4b536e4ccdc3413bd

jobs:
  linux:
    strategy:
      fail-fast: true
      matrix:
        args:
          - triplet: x64-linux
            runner_image: ubuntu-24.04

    runs-on: ${{ matrix.args.runner_image }}
    name: ${{ matrix.args.triplet }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y nasm

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: ./.github/actions/vcpkg-setup

      - name: Install vcpkg packages
        run: vcpkg install --overlay-ports=ports --overlay-triplets=triplets --triplet ${{ matrix.args.triplet }} --host-triplet ${{ matrix.args.triplet }}

      - uses: ./.github/actions/vcpkg-export
        with:
          output-name: vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}
          export-type: 7zip

      - name: Store exported vcpkg packages
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}
          path: ${{ github.workspace }}/vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}.7z

  # macos:
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       args:
  #         - triplet: arm64-osx-dynamic
  #           runner_image: macos-15
  #         - triplet: x64-osx-dynamic
  #           runner_image: macos-15-intel
  #   runs-on: ${{ matrix.args.runner_image }}
  #   name: ${{ matrix.args.triplet }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Export GitHub Actions cache environment variables
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
  #           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

  #     - run: brew install autoconf autoconf-archive automake
  #     - run: brew install nasm
  #       if: ${{ matrix.args.triplet == 'x64-osx-dynamic' }}

  #     - uses: ./.github/actions/vcpkg-setup

  #     - name: Install vcpkg packages
  #       run: vcpkg install --overlay-ports=ports --overlay-triplets=triplets --triplet ${{ matrix.args.triplet }} --host-triplet ${{ matrix.args.triplet }}

  #     - uses: ./.github/actions/vcpkg-export
  #       with:
  #         output-name: vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}
  #         export-type: 7zip

  #     - name: Store exported vcpkg packages
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}
  #         path: ${{ github.workspace }}/vcpkg-${{ matrix.args.triplet }}-${{ github.sha }}.7z

  # windows:
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       args:
  #         - triplet: x64-windows-static
  #           runner_image: windows-2022
  #           identifier: x64-windows-2022-static
  #           host_triplet: x64-windows-static

  #         - triplet: arm64-windows-static-md
  #           runner_image: windows-2022
  #           identifier: arm64-windows-2022-static
  #           host_triplet: x64-windows-static

  #         - triplet: x64-windows
  #           runner_image: windows-2022
  #           identifier: x64-windows-2022
  #           host_triplet: x64-windows
  #           store_symbols: true

  #         - triplet: arm64-windows
  #           runner_image: windows-2022
  #           identifier: arm64-windows-2022
  #           host_triplet: x64-windows
  #           store_symbols: true

  #   name: ${{ matrix.args.identifier }}

  #   runs-on: ${{ matrix.args.runner_image }}

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Export GitHub Actions cache environment variables
  #     uses: actions/github-script@v6
  #     with:
  #       script: |
  #         core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
  #         core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

  #   - uses: ./.github/actions/vcpkg-setup

  #   - name: Install vcpkg packages
  #     run: >
  #       vcpkg install --overlay-ports=ports --overlay-triplets=triplets --host-triplet ${{ matrix.args.host_triplet }} --triplet ${{ matrix.args.triplet }}

  #   - uses: ./.github/actions/vcpkg-export
  #     with:
  #       output-name: intermediate
  #       export-type: raw

  #   - name: Move pdb files
  #     working-directory: '${{ github.workspace }}/intermediate'
  #     run: |
  #       robocopy installed pdb/installed *.pdb /S /MOVE
  #       if ($lastexitcode -lt 8) {
  #         $global:LASTEXITCODE = $null
  #       }

  #   - name: Archive pdb files
  #     working-directory: '${{ github.workspace }}/intermediate/pdb'
  #     run: 7z a "${{ github.workspace }}/vcpkg-${{ matrix.args.identifier }}-pdb-${{ github.sha }}.7z" installed

  #   - name: Store archived pdb files
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: vcpkg-${{ matrix.args.identifier }}-pdb-${{ github.sha }}
  #       path: ${{ github.workspace }}/vcpkg-${{ matrix.args.identifier }}-pdb-${{ github.sha }}.7z

  #   - name: Archive everything else
  #     working-directory: '${{ github.workspace }}/intermediate'
  #     run: 7z a "${{ github.workspace }}/vcpkg-${{ matrix.args.identifier }}-${{ github.sha }}.7z" * -x!pdb

  #   - name: Store exported vcpkg packages
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: vcpkg-${{ matrix.args.identifier }}-${{ github.sha }}
  #       path: ${{ github.workspace }}/vcpkg-${{ matrix.args.identifier }}-${{ github.sha }}.7z

  #   - name: Repackage binaries for symbol server
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     if: ${{ matrix.args.store_symbols && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
  #     run: .\Store-Symbols.ps1 ${{ github.workspace }}\intermediate

  #   - name: Upload symbols to symbol server
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       AWS_DEFAULT_REGION: eu-west-3
  #     if: ${{ matrix.args.store_symbols && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
  #     working-directory: ${{ github.workspace }}/SymStore
  #     run: aws --endpoint-url https://rgw.ctrl-c.liu.se s3 sync --size-only --exclude * --include *.dl_ --include *.pd_ . s3://openmw-sym

  upload-deps:
    needs:
      # - windows
      # - macos
      - linux

    runs-on: ubuntu-latest

    env:
      file: TEST

    permissions:
      contents: write

    # non-master or tagged master only
    if: ${{ github.ref_name != 'master' }}

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Set file name
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "file=${{ github.ref_name }}" >> "$GITHUB_ENV"

    - name: Rename artifacts
      run: |
        mv vcpkg-x64-windows-2022-${{ github.sha }}/vcpkg-x64-windows-2022-${{ github.sha }}.7z vcpkg-x64-windows-2022-${{ env.file }}.7z
        mv vcpkg-x64-windows-2022-pdb-${{ github.sha }}/vcpkg-x64-windows-2022-pdb-${{ github.sha }}.7z vcpkg-x64-windows-2022-pdb-${{ env.file }}.7z
        mv vcpkg-arm64-windows-2022-${{ github.sha }}/vcpkg-arm64-windows-2022-${{ github.sha }}.7z vcpkg-arm64-windows-2022-${{ env.file }}.7z
        mv vcpkg-arm64-windows-2022-pdb-${{ github.sha }}/vcpkg-arm64-windows-2022-pdb-${{ github.sha }}.7z vcpkg-arm64-windows-2022-pdb-${{ env.file }}.7z
        mv vcpkg-arm64-osx-dynamic-${{ github.sha }}/vcpkg-arm64-osx-dynamic-${{ github.sha }}.7z vcpkg-arm64-osx-dynamic-${{ env.file }}.7z
        mv vcpkg-x64-osx-dynamic-${{ github.sha }}/vcpkg-x64-osx-dynamic-${{ github.sha }}.7z vcpkg-x64-osx-dynamic-${{ env.file }}.7z
        mv vcpkg-x64-linux-${{ github.sha }}/vcpkg-x64-linux-${{ github.sha }}.7z vcpkg-x64-linux{{ env.file }}.7z

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: vcpkg-*-${{ env.file }}.7z

    - name: Setup ssh-agent
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      if: ${{ env.SSH_PRIVATE_KEY != '' }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Import GPG key
      id: import_gpg
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      if: ${{ env.GPG_PRIVATE_KEY != '' && env.GPG_PRIVATE_KEY_PASSPHRASE != '' }}
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

    - name: Configure ssh known hosts for gitlab.com
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      if: ${{ env.SSH_PRIVATE_KEY != '' }}
      run: cat gitlab_known_hosts >> ~/.ssh/known_hosts

    - name: Configure git user
      run: |
        git config --global user.email 'openmw-deps-build@users.noreply.github.com'
        git config --global user.name 'openmw-deps-build'

    - name: Configure git sign key
      if: ${{ steps.import_gpg.outputs.fingerprint != '' }}
      run: |
        git config --global user.signkey ${{ steps.import_gpg.outputs.fingerprint }}
        git config --global commit.gpgsign true

    - name: Clone openmw-deps repository via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GIT_LFS_SKIP_SMUDGE: 1
        # see https://github.com/git-lfs/git-lfs/issues/5749
        GIT_CLONE_PROTECTION_ACTIVE: false
      if: ${{ env.SSH_PRIVATE_KEY != '' }}
      run: git clone git@gitlab.com:OpenMW/openmw-deps.git

    - name: Clone openmw-deps repository via HTTPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GIT_LFS_SKIP_SMUDGE: 1
        # see https://github.com/git-lfs/git-lfs/issues/5749
        GIT_CLONE_PROTECTION_ACTIVE: false
      if: ${{ env.SSH_PRIVATE_KEY == '' }}
      run: git clone https://gitlab.com/OpenMW/openmw-deps.git

    - uses: ./.github/actions/manifest-setup
      with:
        file-pattern: vcpkg-*-windows-*-${{ env.file }}
        subdirectory: windows

    - uses: ./.github/actions/manifest-setup
      with:
        file-pattern: vcpkg-*-osx-dynamic-${{ env.file }}
        subdirectory: macos

    - uses: ./.github/actions/manifest-setup
      with:
        file-pattern: vcpkg-*-linux-${{ env.file }}
        subdirectory: linux

    - name: Generate commit message
      env:
        GH_TOKEN: ${{ github.token }}
      working-directory: ${{ github.workspace }}/openmw-deps
      run: |
        echo Add vcpkg package urls built at ${{ github.sha }} > commit_message.txt
        echo >> commit_message.txt
        printf 'Pushed by ' >> commit_message.txt
        url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "upload-deps") | .url')
        echo "${url:?}" >> commit_message.txt
        echo >> commit_message.txt

    - name: Commit generated metadata
      working-directory: ${{ github.workspace }}/openmw-deps
      run: |
        git checkout -b vcpkg-${{ github.sha }}
        git add windows/vcpkg-*-manifest.txt
        git add macos/vcpkg-*-manifest.txt
        git add linux/vcpkg-*-manifest.txt
        git commit -F commit_message.txt

    - name: Verify commit to openmw-deps repository
      if: ${{ steps.import_gpg.outputs.fingerprint != '' }}
      working-directory: ${{ github.workspace }}/openmw-deps
      run: git verify-commit HEAD

    - name: Push generated metadata to gitlab
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # Make sure only signed commits are pushed
      if: ${{ vars.PUSH_URL != '' && env.SSH_PRIVATE_KEY != '' && steps.import_gpg.outputs.fingerprint != '' }}
      working-directory: ${{ github.workspace }}/openmw-deps
      run: |
        git remote set-url --push origin "${{ vars.PUSH_URL }}"
        git push origin vcpkg-${{ github.sha }}
